server:
  port: 8081
spring:
  application:
    name: app-financas
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  flyway:
    url: ${FLYWAY_URL}
    schemas: app-financas
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

resilience4j:
  ratelimiter:
    instances:
      create-user:
        limit-for-period: 3
        limit-refresh-period: 60s
      login:
        limit-for-period: 2
        limit-refresh-period: 60s
      get-user:
        limit-for-period: 1
        limit-refresh-period: 20s
      create-wallet:
        limit-for-period: 3
        limit-refresh-period: 60s

