FROM openjdk:17-jdk-slim
VOLUME /tmp
ARG JAR_FILE=app/target/*.jar
COPY ${JAR_FILE} app.jar
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]